name: Simple Merge Queue Test

on:
  merge_group:
    branches: [ main ]

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build, tag, and push docker image to Amazon ECR
        id: build-image
        run: |
          echo "This build will fail!"
          ./badcommand.sh
          exit 1
